# App name
spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:mysql://172.21.141.161:3306/cms
spring.datasource.username=root
spring.datasource.password=q4F69759v1sSr7PWf3oUjD5Y
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:gCfy4cbfCkA4rRq1dJmNh8mi@172.21.190.218:27017/prescriptions

management.endpoint.health.show-details=always
management.health.db.enabled=true